### ISSUE TITLE
Rename this flasher

### ISSUE THREAD

**Issue by jason0597** [d3m3vilurr/ak2i_ntrcardhax_flasher#10]
It doesn't flash *just* the ak2i, it flashes every ntrboot compatible flashcart. Name is misleading now.
Also, this isn't about ntrcardhax. That hack is looong dead (since 10.4) and it is unrelated to the bootROM backdoor, named NTRBoot

**Comment by d3m3vilurr** [comment]
a month ago, me and ntrboot_flasher team had conversation about this.
I'll not change repo name until to move organization group.
change repo name is also harmful.
