### ISSUE TITLE
Combine the two flashers into one

### ISSUE THREAD

**Issue by jason0597** [d3m3vilurr/ak2i_ntrcardhax_flasher#11]
Because if you run the DSi flasher on a DS lite it still works, I suggest simply removing the already existing NDS flasher and just have the DSi flasher available for download, so that noobs don't mix this step up (i've seen it happen)

**Comment by d3m3vilurr** [comment]
I know. but nds mode can restore flashcart. that is a reason of why I release multiple binaries.
