### ISSUE TITLE
R4I SDHC 3DS RTS NOT SUPPORTED

### ISSUE THREAD

**Issue by yoshigamer478** [d3m3vilurr/ak2i_ntrcardhax_flasher#14]
Me Among Many others have purchased the R4I SDHC 3DS RTS thinking that it was the R4i gold 3ds rts and that is verry confusing so if you could please try and add support for this DS flash cart if you cant thats ok i know its verry hard to develope support for more flash cards but if you could put this one into consideration it would be greatly apprecative http://www.r4i-sdhc.com/aboute.asp One last note i thought the makers of this card released their own flasher but i was deeply mistaken http://www.r4i-sdhc.com/B9SSector.asp

**Comment by d3m3vilurr** [comment]
kitling/flashcart_core#14
