### ISSUE TITLE
Unknown Device

### ISSUE THREAD

**Issue by JHChampion17** [d3m3vilurr/ak2i_ntrcardhax_flasher#15]
I am attempting to flash my DSTT with ntrboot using my DS Lite, and receive the flashcart error. When I run the DSTT Flash Checker, I receive this: unknown device : 20504F54 Good! (^^)v

Any ideas, or future support, would be great. Thanks!

**Comment by d3m3vilurr** [comment]
Not supported & report to kitling/flashcart_core
