### ISSUE TITLE
DSTT stuck at "Reading 99%" while injecting.

### ISSUE THREAD

**Issue by kloklojul** [d3m3vilurr/ak2i_ntrcardhax_flasher#16]
The newest version does not support some DSTT flashcard that were supported in the older version. 
I tried this http://www.nds-card.com/ProShow.asp?ProID=157 DSTT with version 3.1 and it got stuck at the reading process while injecting. Switching to the older 3.0 fixed the issue for me and everything worked fine.

**Comment by d3m3vilurr** [comment]
can you retest newer version?

**Comment by kloklojul** [comment]
I tested it with 3.2 and it seems to work. 
Injecting works.
Restoring works.
