### ISSUE TITLE
Update flashcart_core with support of new flashcarts

### ISSUE THREAD

**Issue by nsuchy** [d3m3vilurr/ak2i_ntrcardhax_flasher#17]
flashcart_core was updated with support for a variety of new flashcarts. This tool should be updated to use the latest flashcart_core and support it's newly supported cards.

**Comment by pbanj** [comment]
it's called waiting. it will get done when it gets done. this issue was completely pointless. if you want it done faster you should do it and make a pull request

**Comment by d3m3vilurr** [comment]
done. https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/releases/tag/v3.2
