### ISSUE TITLE
R4i 3DS Gold Pro

### ISSUE THREAD

**Issue by Nyvia** [d3m3vilurr/ak2i_ntrcardhax_flasher#19]
This flashcart doesn't seem to work with the flasher. It's the 2017 model that's the same hardware as basically every other cart on r4isdhc.com. it's been confirmed as working with the flashcart-flasher from kitling but doesn't work here, according to people with the same cart as I.

**Comment by bcecchinato** [comment]
Tested as well on this card : 
![R4i Gold pro 2017](https://user-images.githubusercontent.com/27431883/29281608-578c0658-80e5-11e7-9440-ad33e7630d31.JPG)

When running the flasher, the error "Flashcart setup failed" is displayed. I've tried to rebuild a flasher version with the DEBUG flag, but no other logs are prompted.

Regards,

**Comment by Nyvia** [comment]
Yep that's the cart I'm using (sans the crooked label).

**Comment by Endmost** [comment]
I have the same problem using the following card:
![img_20171015_123919](https://user-images.githubusercontent.com/32812953/31584098-ba24c5d2-b1a7-11e7-8a73-f3a3ae7febef.jpg)

**Comment by Marioddd1** [comment]
I had the same issue, however with the 2016 version of the same cart. 
![20171015_084512](https://user-images.githubusercontent.com/32814793/31584897-8a14fa0a-b185-11e7-961d-2b18e23fb00c.jpg)

**Comment by pbanj** [comment]
add me to the list. i have a 2014. the ntrboot flasher works but not this

**Comment by Nyvia** [comment]
Confirmed as still not working on 3.3.

**Comment by jechus** [comment]
@Marioddd1 same here

**Comment by Radtendo** [comment]
Hopefully it's added as a compatible cart in a later update. Until then we'l just have to wait. Which for CFW is very worth it.

**Comment by Nyvia** [comment]
It seems that it does work on DS/DS Lites though. It's an issue with DSis

**Comment by Radtendo** [comment]
Sadly no, this specific cart that me and OP have don't work. I've tried it on my DSLite several times. Someone else even confirmed it isn't supported yet. 
There's a way to get the hax to recognize the cart but it isn't worth it seeing as it usually just gets stuck trying to flash onto an unsupported cart.

**Comment by Nyvia** [comment]
Confirmed as working on this card now
