### ISSUE TITLE
R4i SDHC RTS Lite

### ISSUE THREAD

**Issue by Parpalloto** [d3m3vilurr/ak2i_ntrcardhax_flasher#22]
This flashcard is supposed to work, but when I try to flash it, it does nothing.

**Comment by knowbeard** [comment]
Short Version: Takes a while to register card then doesn't proceed past 0% while writing nor.
Long Version:

When using the nds flasher, I get to the screen saying 

`<A> Inject ntrboothax`
`<B> Return`

at this point pressing A changes the bottom screen to display

`flashcart`
`press <A>`

Pressing A returns to the previous screen, with A to inject and B to return.

Removing and reinserting the flashcard occasionally lets the "Inject ntrboothax" option work, and I'm asked to press A for retail, X for dev and B to return.

Selecting retail or dev brings up the "Writing NOR" screen but it's stuck at 0%.
Selecting B to return brings up the `flashcart`  `press <A>` menu and I have to remove and reinsert the flashcart a few times until it will register again and ask to inject ntrboothax.

Couldn't take any decent pictures so sorry for the lengthy post!
