### ISSUE TITLE
DSTT Micron MT28F160C3 (4)-T stuck

### ISSUE THREAD

**Issue by Dio89** [d3m3vilurr/ak2i_ntrcardhax_flasher#28]
tested 3.3 - Stuck at Erasing blocks at 0%
tested 3.2- Stuck at the first part (loading firmware?) at 99%
Does not work on previous versions at all. I checked the list of incompatible DSTT flash chips but MT28F160C3 (4)-T is not included.

If i removed the flashcart during the process then put it back again, it somehow skips the erasing blocks part then continues to Flash ntrboot up to 6%. Not sure if that helps.

**Comment by d3m3vilurr** [comment]
probably [not support](https://github.com/kitling/flashcart_core/blob/b2239235755/devices/dstt.cpp#L71)
make comment to kitling/flashcart_core#56
