### ISSUE TITLE
blowfish_ntr.bin

### ISSUE THREAD

**Issue by Sempiternalsharp** [d3m3vilurr/ak2i_ntrcardhax_flasher#30]
Since there is now a new requirement when compiling ("blowfish_ntr.bin"), I would like to know where I can get it, so I can compile manually.

**Comment by d3m3vilurr** [comment]
https://github.com/d3m3vilurr/ak2ifirm/commit/3fedaefc788204f6459cc73f3f40bfda1640e21f you can generate from boot11.bin

**Comment by Fachher** [comment]
Is it device specific or could you share it with any one-click hoster?
