### ISSUE TITLE
DSTT Micron MT28F160C3_3 0x922c Not Working

### ISSUE THREAD

**Issue by herrfridolin** [d3m3vilurr/ak2i_ntrcardhax_flasher#31]
The flashcard gets stuck on 99% reading using latest build. Is there more information/testers you need for that card? Your supported list says it should be supported, but requires a different flash method... I'm creating this issue because i haven't noticed any other issue about a similar, non standard card.

**Comment by d3m3vilurr** [comment]
ntrteam/flashcart_core#56
