### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by NicknameGoesHere** [d3m3vilurr/ak2i_ntrcardhax_flasher#4]
Trying to test with newer NTRBOOT Cores.

**Comment by d3m3vilurr** [comment]
what is newer ntrboot core? anyway download nds file and copy to flashcart's sdcard. then load on your device.

**Comment by Juanito9001** [comment]
What is that newew NTRBOOT CORE??? 

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by d3m3vilurr** [comment]
if you are said about flashcart_core, not updated yet.

**Comment by Valeri0p** [comment]
Are you sure?
https://github.com/kitling/flashcart_core/commit/f404062246a2d3313e77ea99ecbfe9da6823da16

https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/tree/master/external

**Comment by NicknameGoesHere** [comment]
How do you use this and end up with a .nds file
