### ISSUE TITLE
[Suggestion] Another R4i

### ISSUE THREAD

**Issue by anuserlol** [d3m3vilurr/ak2i_ntrcardhax_flasher#5]
A bunch of friend and I bought some R4i V1.4 Upgrade GE (Etc,etc,etc...) and they said that if I could ask you.
Can you add this other flashcard please?
The flashcard looks like this: 
http://imgur.com/a/tIq30
Thank you for reading!

(Also except for one of us, we have got DSi 's

**Comment by MilkyPL** [comment]
You should ask on [kitling/flashcart_core](https://github.com/kitling/flashcart_core), it handles flashcart specific behavior.
